version: '3.4'
services:
  back:
    image: omaroukil/crudapp:back
    ports:
      - "2022:2022"
  front:
    image: omaroukil/crudapp:front
    ports:
      - "80:80"
    depends_on:
      - back
      